version: "3.8"
services:
  nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi01
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - /Users/f.areias/Documents/Courses/NiFi/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - /Users/f.areias/Documents/Courses/NiFi/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - /Users/f.areias/Documents/Courses/NiFi/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - /Users/f.areias/Documents/Courses/NiFi/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - /Users/f.areias/Documents/Courses/NiFi/nifi/state:/opt/nifi/nifi-current/state
      - /Users/f.areias/Documents/Courses/NiFi/nifi/logs:/opt/nifi/nifi-current/logs
    networks:
      - treinamento

  registry:
    hostname: myregistry
    container_name: registry_container_persistent
    image: "apache/nifi-registry:1.15.0" # latest image as of 2021-11-09.
    restart: on-failure
    ports:
      - "18080:18080"
    environment:
      - LOG_LEVEL=INFO
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    volumes:
      - ./nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
      - ./nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - treinamento

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
    networks:
      - treinamento
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - /Users/f.areias/Documents/Courses/NiFi/postgresql/scripts_sql:/docker-entrypoint-initdb.d

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - treinamento

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:2181
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - treinamento

  connect:
    image: "debezium/connect"
    environment:
      GROUP_ID: 1
      REST_ADVERTISED_HOST_NAME: "connect"
      BOOTSTRAP_SERVERS: "host.docker.internal:9092"
      ZOOKEEPER_CONNECT: "host.docker.internal:2181"
      CONFIG_STORAGE_TOPIC: "my_connect_configs"
      OFFSET_STORAGE_TOPIC: "my_connect_offsets"
      STATUS_STORAGE_TOPIC: "my_connect_statuses"
    ports:
      - "8083:8083"
    container_name: "connect"
    networks:
      - treinamento

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:9092

networks:
  treinamento:
    driver: bridge
